name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: '1.25.1'

    - name: Update dependencies
      run: |
        go get -u all
        go mod tidy

    - name: Build all platforms
      run: |
        # Linux AMD64
        GOOS=linux GOARCH=amd64 go build -o github-profiler-linux-amd64 .
        
        # Linux ARM64
        GOOS=linux GOARCH=arm64 go build -o github-profiler-linux-arm64 .
        
        # macOS AMD64
        GOOS=darwin GOARCH=amd64 go build -o github-profiler-darwin-amd64 .
        
        # macOS ARM64 (Apple Silicon)
        GOOS=darwin GOARCH=arm64 go build -o github-profiler-darwin-arm64 .
        
        # Windows AMD64
        GOOS=windows GOARCH=amd64 go build -o github-profiler-windows-amd64.exe .

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: github-profiler-builds
        path: github-profiler-*
        retention-days: 7
