name: Test Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.4'

    - name: Run build
      run: |
        echo "Running make build-all"
        make build-all

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: go-build
        path: build/

    - name: Build completed
      run: echo "Build and artifact upload completed."
