name: Renovate

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * 1' # Every Monday at 2:00 AM UTC

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Renovate Bot
        uses: renovatebot/github-action@v43.0.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
